-- CREATE THE DATABASE IF EXISTS
DROP DATABASE IF EXISTS burgers_db;
CREATE DATABASE burgers_db;

USE burgers_db;

-- CREATE BURGERS TABLE
CREATE TABLE burgers (
	id INT AUTO_INCREMENT NOT NULL,
	burger_name VARCHAR(255),
	devoured BOOLEAN DEFAULT false,
	CREATE  At TIMESTAMP NOT NULL,
	PRIMARY KEY(id)
);